#!/bin/bash
export CATALINA_BASE1=catalina_base
LOG=`date --date='1 months ago' +%Y-%m`
source ${SHELL}/${DOMAIN}/env.sh
#########################starting#############
start()
{
for CATALINA_BASE in $CATALINA_BASE1
    do
        echo "*****************************************"
        echo "***       tomcat starting action      ***"
        echo "*****************************************"

        rm -fr $CATALINA_BASE/logs/*$LOG*
        $CATALINA_BASE/bin/start.sh|awk '{printf "..."}END{print "Finished"}'
        if [[ $? == 0 ]];then
            echo "###########################"
            echo "#tomcat started succeed!! #"
            echo "###########################"
        fi
    done
    tail -f $CATALINA_BASE/logs/catalina.out
}

#########################stoping####################
stop()
{
for CATALINA_BASE in $CATALINA_BASE1
    do
        echo "*****************************************"
        echo "***       tomcat stoping action       ***"
        echo "*****************************************"

        $CATALINA_BASE/bin/stop.sh |awk '{printf "..."}END{print "Finished"}'
        ps -aef | grep java|grep "$CATALINA_BASE" |grep -v grep |sed 's/ [ ]*/:/g' |cut -d: -f2|kill -9 `cat`

        if [[ $? == 0 ]];then
            echo "###########################"
            echo "# tomcat stoped succeed!! #"
            echo "###########################"
        fi
    done
}
#######################restarting#####################
restart()
{
    stop
    start
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    ?|help)
        echo $"使用命令格式: $0 {start|stop|restart|help|?}"
        ;;
    *)
    restart
esac
