#!/bin/bash
source ${SHELL}/${DOMAIN}/env.sh
TOMCAT_HOME=${INSTANCE}/${DOMAIN}
################ tomcat start ####################
start()
{
    for catalina in `ls ${TOMCAT_HOME}`;do
        echo "=====  tomcat${COUNT} starting action  ====="
        export CATALINA_BASE=${TOMCAT_HOME}/${catalina}
        ${CATALINA_HOME}/bin/startup.sh -config ${CATALINA_BASE}/conf/server.xml |awk '{print }'
#        $CATALINA_BASE/bin/start.sh |awk '{printf "..."}END{print "Finished"}'
        if [ $? == 0 ];then
            echo -e "=====  tomcat${COUNT} started succeed  ===== \n\n"
        fi
    done
    echo "===== ${CATALINA_BASE}/logs/catalina.out ====="
    tail -f ${CATALINA_BASE}/logs/catalina.out
}

################# tomcat stop ####################
stop()
{
    for catalina in `ls ${TOMCAT_HOME}`;do
        echo "=====  tomcat${COUNT} stopping action  ====="
        export CATALINA_BASE=${TOMCAT_HOME}/${catalina}
        ${CATALINA_HOME}/bin/shutdown.sh -config ${CATALINA_BASE}/conf/server.xml
        if [ $? == 0 ];then
            PID=`ps -aef | grep java|grep ${CATALINA_BASE}| grep -v grep | sed 's/ [ ]*/:/g'|cut -d: -f2`
            if [ ${PID} ];then
                echo "  kill process，pid=${PID}"
                kill -9 ${PID}
            fi
        fi
        echo -e "=====  tomcat${COUNT} stopped succeed  =====\n\n"
    done
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    ?|help)
        echo $"使用命令格式: $0 {start|stop|restart|help|?}"
        ;;
    *)
        stop
        start
        ;;
esac
